# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NuGet Pack & Push

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:      
    
jobs:
  build:

    runs-on: windows-latest
    
    env:
      Configuration: Release
      Solution: TG.Common.sln
      PkgProject: src/TG.Common/TG.Common.csproj
      Test_Project_Path: tests/UnitTests/UnitTests.csproj

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution /t:Restore /p:Configuration=$env:Configuration

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path

    - name: Pack
      run: msbuild $env:PkgProject /t:pack /p:Configuration=$env:Configuration
    
    - name: Setup NuGet.exe for use with actions
      # You may pin to the exact commit or the version.
      # uses: NuGet/setup-nuget@fd9fffd6ca4541cf4152a9565835ca1a88a6eb37
      uses: NuGet/setup-nuget@v1.1.1
      env:

      with:
        # NuGet version to install. Can be `latest`, `preview`, a concrete version like `5.3.1`, or a semver range specifier like `5.x`.
        nuget-version: # optional, default is latest
        # NuGet API Key to configure.
        nuget-api-key: # optional
        # Source to scope the NuGet API Key to.
        nuget-api-key-source: https://api.nuget.org/v3/index.json

    - name: Push to NuGet.org
      run: dotnet nuget push "src\TG.Common\bin\Release\*.nupkg" --api-key "$NUGET_TOKEN" --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}

    # - name: Push symbol package to NuGet.org
    #   run: dotnet nuget push "src\TG.Common\bin\Release\*.snupkg" --api-key "$NUGET_TOKEN" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
    #   env:
    #     NUGET_TOKEN: ${{ secrets.NUGET_KEY }}

